name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: GitHub Action for Sanity.ioGitHub Action for Sanity.io
    - name: sanity-io/github-action-sanity@v0.1-alpha
      run: echo Hello, world!
    - name: Run a multi-line script
      
     
  uses: actions/setup-dotnet@v1.4.0
  with:
    # SDK version to use. Example: 2.2.104
    dotnet-version: # optional
    # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
    source-url: # optional
    # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url
    owner: # optional
    # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
    config-file: # optional
    # Deprecated. Use dotnet-version instead. Will not be supported after October 1, 2019
    version: # optional 
       
  
        echo Add other actions to build,
        echo test, and deploy your project.
        name:fiery-bonbon-228715;
  on: "pull request;"

action "validate license" }

  args = ["MIT,ISC"]
  - name: Setup Node.js for use with actions
  uses: actions/setup-node@v1.1.0- name: Download artifact
  uses: actions/download-artifact@v1.0.0
  with:
    # Artifact name
    name: 
    # Destination path
    path: # optional
  with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
    version: # optional, default is 10.x
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
    registry-url: # optional
    # Optional scope for authenticating against scoped registries 
    scope: # optional
}

